name: "Refresh Submodules Commit ID"

on:
  push:
    branches: [ "gh-pages" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Recreate submodules commit ID list file."
        run: |
          rm -f _includes/submod_hashes.html
          touch _includes/submod_hashes.html
      - name: "Fetch submodules commit IDs."
        run: |
          git submodule status | while read line; do
            if [ "${line}" ]; then
              commit_id=$(echo ${line} | sed -e 's/^\s*\([0-9A-Za-z]\+\)\s\+\([0-9A-Za-z/_-]\+\)\s\+([0-9A-Za-z/_-]\+)\s*$/\1/g')
              submoddir=$(echo ${line} | sed -e 's/^\s*\([0-9A-Za-z]\+\)\s\+\([0-9A-Za-z/_-]\+\)\s\+([0-9A-Za-z/_-]\+)\s*$/\2/g')
              submoddir=$(echo ${submoddir} | sed -e 's/[^0-9A-Za-z_]/_/g')
              echo {% assign commit_id_for_${submoddir}=\"${commit_id}\" %}>>_includes/submod_hashes.html
            fi
          done
      - name: "Configure git user information."
        run: |
          git config --local user.email "noreply@localhost"
          git config --local user.name "[BOT] Refresh Submodules Commit ID"
      - name: "Commit & Push"
        run: |
          git add .
          git commit -m "Update _includes/submod_hashes.html"
          git push
